name: Check Base Image Updates and Rebuild

on:
  #schedule:
    # Esegui ogni giorno alle 04:00 UTC per controllare gli aggiornamenti.
  #  - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-images:
    uses: Neomediatech/gh-workflows/.github/workflows/check-and-build-docker-images.yml@main
    with:
      base-image: ghcr.io/rspamd/rspamd-docker:latest
      derived-image-prefix: ghcr.io/neomediatech/rspamd
      versions: '["latest", "3.8", "3.6"]'

