name: Get Docker Image Info

on:
  workflow_call:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub

jobs:
  get_info:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Install Skopeo (if not already present)
      #  run: sudo apt-get update && sudo apt-get install -y skopeo

      - name: Get Base Image Digest
        id: get_digest
        run: |
          # Ottieni il manifest completo dell'immagine base
          # Reindirizza stderr a stdout per catturare gli errori nell'output
          # se è un'immagine ufficiale bisogna aggiungere "docker.io/library"
          MANIFEST_OUTPUT=$(skopeo inspect docker://ghcr.io/neomediatech/rspamd 2>&1)

          PARSED_DIGEST=$(echo "$MANIFEST_OUTPUT" | jq -r '.Digest' 2>/dev/null)

          if [ -z "$PARSED_DIGEST" ] || [ "$PARSED_DIGEST" == "null" ]; then
              echo "::error::Failed to get valid digest for base image: $FULL_BASE_IMAGE for $TARGET_OS/$TARGET_ARCH"
              echo "::error::Raw output of 'docker manifest inspect $FULL_BASE_IMAGE':"
              echo "$MANIFEST_OUTPUT"
              exit 1
          fi

          echo "Base Image Digest: $PARSED_DIGEST"
          echo "base_image_digest=$PARSED_DIGEST" >> "$GITHUB_OUTPUT"
        shell: bash
    outputs:
      base_image_digest: ${{ steps.get_digest.outputs.base_image_digest }}
